version: '3'

services:
  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  invoker:
    build:
      context: ./invoker
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - generator
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"